name: clothing_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  velocity_x: ^4.3.1
  form_field_validator: ^1.1.0
  flutter_vector_icons: ^1.0.0
  provider: ^6.0.3
  video_player: ^2.9.2
  image_picker: ^1.1.2
  http: ^1.2.2
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - videos/
    - assets/icon/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A1B33"
  adaptive_icon_foreground: "icon/icon.png"

flutter_native_splash:
  color: "#0A1B33"
  image: assets/icon/icon.png
  android_12:
    color: "#021032"
    image: assets/icon/icon.png
